name: AWS Authentication

on: [push, pull_request]



jobs:
  aws-auth:
    runs-on: ubuntu-latest

    permissions:
        id-token: write   # This is required for requesting the JWT
        contents: write    # This is required for actions/checkout

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Configure AWS credentials using OIDC
    - name: Configure AWS credentials using OIDC
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/Github-Runners-Access
        role-session-name: GitHub_to_AWS_via_FederatedOIDC_Run_ID_${{ github.run_id }} 
        aws-region: eu-west-1
        output-credentials: true

    # Install AWS CLI
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Verify AWS identity
      run: |
        aws sts get-caller-identity

    - name: Run your build or deployment steps
      run: |
        # Add your build or deployment steps here
        echo "Running build or deployment steps..."
